name: Terraform Security Scan & Plan

on:
  push:
    branches:
      - main

# permissions:
#   id-token: write
#   contents: read

jobs:
  Terraform-validate-plan:
    name: security scan & plan 
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7.0.1
  
      - name:  Run checkout Security scan
        uses:  bridgecrewio/checkov-action@v12

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Hashicorp - setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1

      - name: Terraform Init
        run:  terraform init 
        working-directory: ./pipeline_infra

      - name: Terraform Format Check
        run:  terraform fmt -check
        working-directory: ./pipeline_infra

      - name: Terraform Validate
        run:  terraform validate
        working-directory: ./pipeline_infra

      - name: Terraform Plan
        run:  terraform plan
        working-directory: ./pipeline_infra


         



